version: "3.8"

services:
  frontend:
    build: ./todoapp-frontend-nextjs-plasmic
    image: frontend
    ports:
      - 3000:3000
    volumes:
      - ./todoapp-frontend-nextjs-plasmic:/app
    depends_on:
      - backend
  backend:
    build: ./todoapp-backend-django
    image: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./todoapp-backend-django:/app
    ports:
      - 8000:8000
    env_file:
      - ./todoapp-backend-django/.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
