// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5BwtKaPW69DtLKD2yetQK2
// Component: 6ge1vqgUce
import * as React from "react";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: Hei_5iCMTfR/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_todo_app_practice.module.css"; // plasmic-import: 5BwtKaPW69DtLKD2yetQK2/projectcss
import sty from "./PlasmicTaskListItem.module.css"; // plasmic-import: 6ge1vqgUce/css

export const PlasmicTaskListItem__VariantProps = new Array();

export const PlasmicTaskListItem__ArgProps = new Array("task");

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTaskListItem__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return true ? (
    <div
      data-plasmic-name={"taskListItem"}
      data-plasmic-override={overrides.taskListItem}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.taskListItem
      )}
    >
      <div
        data-plasmic-name={"taskText"}
        data-plasmic-override={overrides.taskText}
        className={classNames(projectcss.all, sty.taskText)}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Item No.1",
          value: args.task,
          className: classNames(sty.slotTargetTask)
        })}
      </div>
      <Button
        data-plasmic-name={"deleteButton"}
        data-plasmic-override={overrides.deleteButton}
        className={classNames("__wab_instance", sty.deleteButton)}
        color={"red"}
      >
        {"Delete"}
      </Button>
    </div>
  ) : null;
}

const PlasmicDescendants = {
  taskListItem: ["taskListItem", "taskText", "deleteButton"],
  taskText: ["taskText"],
  deleteButton: ["deleteButton"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTaskListItem__ArgProps,
          internalVariantPropNames: PlasmicTaskListItem__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTaskListItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "taskListItem") {
    func.displayName = "PlasmicTaskListItem";
  } else {
    func.displayName = `PlasmicTaskListItem.${nodeName}`;
  }
  return func;
}

export const PlasmicTaskListItem = Object.assign(
  // Top-level PlasmicTaskListItem renders the root element
  makeNodeComponent("taskListItem"),
  {
    // Helper components rendering sub-elements
    taskText: makeNodeComponent("taskText"),
    deleteButton: makeNodeComponent("deleteButton"),
    // Metadata about props expected for PlasmicTaskListItem
    internalVariantProps: PlasmicTaskListItem__VariantProps,
    internalArgProps: PlasmicTaskListItem__ArgProps
  }
);

export default PlasmicTaskListItem;
/* prettier-ignore-end */
